### ISSUE TITLE
nvim config seems to be incomplete

### ISSUE THREAD

**Issue by flamedmg** [petertriho/dotfiles#47]
Hello, tried to use your nvim config, but cant' start it. It seems your forgot to add impatient.lua file

**Comment by petertriho** [comment]
@flamedmg Sorry, I didn't see your issue,  wasn't expecting anyone to use my dotfiles. My setup is a bit funky. On new installs, you need to comment out this line, `PackerSync` then it'll work. This is because https://github.com/lewis6991/impatient.nvim isn't installed yet.

**Comment by flamedmg** [comment]
Yeah, this is what i've done to make it work :) I really love how your vim is themed, but can't use your config, is way different from what i used to in terms of keymaps and plugins

**Comment by petertriho** [comment]
I highly recommend you start from scratch and take bits of pieces from different configs. I'm happy to help out!
